[package]
name = "slipv6"
version = "0.1.0"
edition = "2021"

[dependencies.tokio]
version = "1"
features = ["net", "rt-multi-thread", "macros", "io-util"]

[dependencies]
anyhow = "1"
nix = { version = "0.24", features = ["ioctl", "net"] }
futures = "0.3"
serial-line-ip = "0.5"
termios = "0.3"
